{
  "0 debug pnpm:scope": {
    "selected": 1,
    "workspacePrefix": "/home/sovlookup/桌面/rubickbase"
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "Command failed with ENOENT: ok\nspawn ok ENOENT",
      "code": "ENOENT",
      "stack": "Error: Command failed with ENOENT: ok\nspawn ok ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)\n    at onErrorNT (node:internal/child_process:477:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  },
  "2 error pnpm": {
    "errno": -2,
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "syscall": "spawn ok",
    "path": "ok",
    "spawnargs": [],
    "originalMessage": "spawn ok ENOENT",
    "shortMessage": "Command failed with ENOENT: ok\nspawn ok ENOENT",
    "command": "ok",
    "escapedCommand": "ok",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false,
    "prefix": "/home/sovlookup/桌面/rubickbase/example",
    "err": {
      "name": "Error",
      "message": "Command failed with ENOENT: ok\nspawn ok ENOENT",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: Command failed with ENOENT: ok\nspawn ok ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)\n    at onErrorNT (node:internal/child_process:477:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    }
  }
}